name: Spellcheck
on:
  push:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  spellcheck:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
      - name: Clone l10n repository
        uses: actions/checkout@v3
        with:
          path: "linter"
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y python-dev-is-python3 libhunspell-dev mercurial
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run checks
        run: |
          # Clone repository
          hg clone https://hg.mozilla.org/l10n-central/it l10n-central

          # Set up config
          echo "[default]" > linter/config/config.ini
          echo "repo_path = $PWD/l10n-central" >> linter/config/config.ini

          # Run checks
          ./linter/scripts/check_strings.sh
