name: Spellcheck
on:
  push:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  spellcheck:
    name: Check spelling
    runs-on: ubuntu-latest
    steps:
      - name: Clone l10n repository
        uses: actions/checkout@v4
        with:
          path: "linter"
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y python-dev-is-python3 libhunspell-dev mercurial
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          version: "0.8.11"
      - name: Clone it folder from firefox-l10n
        uses: actions/checkout@v5
        with:
          repository: mozilla-l10n/firefox-l10n
          path: l10n
          sparse-checkout: |
            it
      - name: Run checks
        run: |
          # Set up config
          echo "[default]" > linter/config/config.ini
          echo "repo_path = $PWD/l10n/it" >> linter/config/config.ini

          # Run checks
          ./linter/scripts/check_strings.sh
